// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxyTPuVRWnpEWShBVEwQNVQRc25iHNOMk',
    appId: '1:683045819902:web:3da802a18ebcd7a6c25caf',
    messagingSenderId: '683045819902',
    projectId: 'flutterauth-d6c56',
    authDomain: 'flutterauth-d6c56.firebaseapp.com',
    storageBucket: 'flutterauth-d6c56.appspot.com',
    measurementId: 'G-5P4R06MYGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUm5AnvLmK73NV14ZcNBCgWV1X2MVcIL4',
    appId: '1:683045819902:android:59e7a629304edd48c25caf',
    messagingSenderId: '683045819902',
    projectId: 'flutterauth-d6c56',
    storageBucket: 'flutterauth-d6c56.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAs3FI5R2FPSDmKxmyNa1BCU-ahnzCFikE',
    appId: '1:683045819902:ios:b26b8228dbac75b1c25caf',
    messagingSenderId: '683045819902',
    projectId: 'flutterauth-d6c56',
    storageBucket: 'flutterauth-d6c56.appspot.com',
    iosClientId: '683045819902-1lckbc0k85q94cb1mkk7jihlejvu3kv3.apps.googleusercontent.com',
    iosBundleId: 'com.example.authGoogle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAs3FI5R2FPSDmKxmyNa1BCU-ahnzCFikE',
    appId: '1:683045819902:ios:edc59eca72c3da86c25caf',
    messagingSenderId: '683045819902',
    projectId: 'flutterauth-d6c56',
    storageBucket: 'flutterauth-d6c56.appspot.com',
    iosClientId: '683045819902-270rebb8i8cttkp0co3v887cba3su7tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.authGoogle.RunnerTests',
  );
}
